### ISSUE TITLE
Loading administrative panel on fresh install throws uncaught exception

### ISSUE THREAD

**Issue by ross-pfahler** [alleyinteractive/apple-news#169]
I just installed the plugin, and navigating to the administrative page results in:
```
2016/05/13 05:17:30 [error] 30890#0: *21972028 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Apple_Push_API\Request\Request_Exception' with message 'MISSING_API_KEY_ID' in /var/www/***/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php:210
Stack trace:
#0 /var/www/***/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php(157): Apple_Push_API\Request\Request->parse_response(Array, true, 'get')
#1 /var/www/***/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(164): Apple_Push_API\Request\Request->get('https://u48r14....')
#2 /var/www/***/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(135): Apple_Push_API\API->send_get_request('https://u48r14....')
#3 /var/www/***/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-section.php(69): Apple_Push_API\API->get_sections('')
#4 /var/www/***/wp-content/plugins/publish-to-apple-news/admi" while reading upstream, client: **
```
- php: PHP 5.5.9-1ubuntu4.11
- wp: 4.5.2
- plugin: 1.1.1

Am I doing something incorrectly? Thanks!

**Comment by bcampeau** [comment]
We're looking into this now

**Comment by ross-pfahler** [comment]
New version looks great! Thanks for the responsive update.

Closing issue.
